language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devops4linux-test
  api_key:
    secure: pTgY2tOeW0BgEZrsYUVd0h5D0X4kHdO2fdMhpDa6AwL3xx6qL4pZ+suPzuxDJPj5HJcCqBtYSxhH0y6XSnJl9IkkSugkC9o5i9ykwByUVLZyIs08DRXKEvc62zT2ZAbL00cMYdocUJbLGYTROx6KfH8gFaokufGO8m43+Cnigdg931UHH7WfhqsIkBoJl0pH4MiuqEXtahQRdBezTQAi9/LXmy3eFgi8EWx3owUrCZR38qqxGzeZOsU2/L20IPgM9Trzea4LASD3SL4OIFATUcIowZi99isoYwhnHF589xSU+ZhJrVv5MS7jzAquFlAd2Rswwh0ionfuyEOxgtxL9BVxlk6t5cftdCWTCjEItLfqQ4ywtacp4SIM8JpBsdtxWaCKLOsBx23Z0o0wY0e0qxR9Ca2LogI+nHGfaJuju5lAb7XPJWCKoCI6pMjRLTF9Mg4SoqeunH4PbfLvrUWtgnxVtIULBq3mw3vH/DkdSfMnFB5MrazRWmCt9U1SjTzjRHgAujZSUBgFkmBaPnvRABBjeR83yLwIAN+/kBchRQiyskCATqJxxdWkXFVtKVfx3wperwTlymnNI28XY/BTIgICDkAf15k/g3KziTPAWg/MM7pJCCUU527R6pKtB5STR04K2pg22/AxFCAo4S1vaHFhJckTrI/Zab4HhmP5720=
